name: Rust CI & Release

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 3 * * 0' # every Sunday at 3 AM UTC - for latest-deps

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build, Test, Lint (stable, beta, nightly)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Lint with Clippy
        if: matrix.toolchain == 'stable'
        run: cargo clippy --all-targets -- -D warnings

      - name: Check formatting
        if: matrix.toolchain == 'stable'
        run: cargo fmt --all -- --check

  latest-deps:
    name: Verify with latest dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo update
      - run: cargo build --verbose
      - run: cargo test --verbose

  msrv:
    name: Verify MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack check --rust-version --workspace --all-targets --ignore-private

  publish:
    name: Publish to crates.io
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Publish crate
        run: cargo publish --locked --token ${{ secrets.PUBLISH }}
